name: Build and Publish Docker

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push (5.4)
        uses: docker/build-push-action@v2
        with:
          context: ./archives/5.4/buster/cli
          file: ./archives/5.4/buster/cli/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/php:5.4-buster

      - name: Build and push (5.5)
        uses: docker/build-push-action@v2
        with:
          context: ./archives/5.5/buster/cli
          file: ./archives/5.5/buster/cli/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/php:5.5-buster

      - name: Build and push (5.6)
        uses: docker/build-push-action@v2
        with:
          context: ./archives/5.6/buster/cli
          file: ./archives/5.6/buster/cli/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/php:5.6-buster
